spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 0000
    url: jdbc:mysql://localhost:3306/blog
    password: 0000
  jpa:
    open-in-view: 'false'
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

cos:
  key: qwe123